=== omarnasir/ID2208_HW1/src/xsdFiles/CompanyInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.employmentservicecompany.org/companyinfo.xsd"
	xmlns:tns="http://www.employmentservicecompany.org/companyinfo.xsd"
	elementFormDefault="qualified">
	<xsd:element name="companyinfo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="company" minOccurs="1" maxOccurs="100">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="companyID" type="xsd:ID"/>
							<xsd:element name="companyName" type="xsd:string" />
							<xsd:element name="registrationNumber" type="tns:registrationNumberType" />
							<xsd:element name="industry" type="tns:IndustryType" />
							<xsd:element name="description" type="tns:descriptionType"
								minOccurs="0" />
							<xsd:element name="size" type="tns:sizeType"
								minOccurs="0" />
							<xsd:element name="location" type="xsd:string" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
    <xsd:simpleType name="IndustryType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="ICT"/>
            <xsd:enumeration value="Electronics"/>
            <xsd:enumeration value="Telecommunication"/>
            <xsd:enumeration value="Computer Science"/>
        </xsd:restriction>
    </xsd:simpleType>
	<xsd:simpleType name="registrationNumberType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]{4}[-][0-9]{6}" /> <!-- Example: 2016-556677 -->
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="descriptionType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1000" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="sizeType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== omarnasir/ID2208_HW1/src/xmlFiles/CompanyInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<cmp:companyinfo
	xmlns:cmp="http://www.employmentservicecompany.org/companyinfo.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.employmentservicecompany.org/companyinfo.xsd ../xsdFiles/CompanyInfo.xsd ">
	<cmp:company>
		<cmp:companyID>idvalue0</cmp:companyID>
		<cmp:companyName>Cloud Computing</cmp:companyName>
		<cmp:registrationNumber>2016-100000</cmp:registrationNumber>
		<cmp:industry>ICT</cmp:industry>
		<cmp:description>Provides cloud infrastructure services.</cmp:description>
		<cmp:size>100</cmp:size>
		<cmp:location>Stockholm</cmp:location>
	</cmp:company>
	<cmp:company>
		<cmp:companyID>idvalue1</cmp:companyID>
		<cmp:companyName>Designers Hub</cmp:companyName>
		<cmp:registrationNumber>2016-100001</cmp:registrationNumber>
		<cmp:industry>ICT</cmp:industry>
		<cmp:description>Provides front-end web designing solution.</cmp:description>
		<cmp:size>20</cmp:size>
		<cmp:location>London</cmp:location>
	</cmp:company>
		<cmp:company>
		<cmp:companyID>idvalue2</cmp:companyID>
		<cmp:companyName>Yahou Company</cmp:companyName>
		<cmp:registrationNumber>2016-100002</cmp:registrationNumber>
		<cmp:industry>Telecommunication</cmp:industry>
		<cmp:description>Provides telecommunication services.</cmp:description>
		<cmp:size>200</cmp:size>
		<cmp:location>Munich</cmp:location>
	</cmp:company>
</cmp:companyinfo>
