=== omarnasir/ID2208_HW1/src/xsdFiles/EmploymentRecords.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.employmentservicecompany.org/employmentrecords.xsd"
            xmlns:tns="http://www.employmentservicecompany.org/employmentrecords.xsd"
            elementFormDefault="qualified">
    <xsd:element name="employmentrecords">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Name" type="xsd:string" minOccurs="1"/>
                <xsd:element name="Records">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Record" minOccurs="1" maxOccurs="30">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Company_Name" type="xsd:string"/>
                                        <xsd:element name="Designation" type="tns:Designation_Type"/>
                                        <xsd:element name="Description" type="tns:Description_Type"/>
                                        <xsd:element name="Starting_year" type="tns:StartingyearType"  />
                                        <xsd:element name="Ending_year" type="tns:EndingyearType"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    	<xsd:simpleType name="StartingyearType">
		<xsd:restriction base="xsd:dateTime">
			<xsd:minInclusive value="1900-01-01T00:00:00" />
			<xsd:maxInclusive value="2100-01-01T00:00:00" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="EndingyearType">
		<xsd:restriction base="xsd:dateTime">
			<xsd:minInclusive value="1900-01-01T00:00:00" />
			<xsd:maxInclusive value="2100-01-01T00:00:00" />
		</xsd:restriction>
	</xsd:simpleType>
    <xsd:simpleType name="Description_Type">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="1000"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="Designation_Type">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="1000"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== omarnasir/ID2208_HW1/src/xmlFiles/EmploymentRecords.xml
<?xml version="1.0" encoding="UTF-8"?>
<emp:employmentrecords xmlns:emp="http://www.employmentservicecompany.org/employmentrecords.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.employmentservicecompany.org/employmentrecords.xsd ../xsdFiles/EmploymentRecords.xsd ">
  <emp:Name>Mr. XYZ</emp:Name>
  <emp:Records>
    <!--1 to 30 repetitions:-->
    <emp:Record>
      <emp:Company_Name>Yahou Company</emp:Company_Name>
      <emp:Designation>TEL2006-112233</emp:Designation>
      <emp:Description>Provides telecommunication services</emp:Description>
      <emp:Starting_year>2007-12-10</emp:Starting_year>
      <emp:Ending_year>2016-01-01</emp:Ending_year>
    </emp:Record>
    <emp:Record>
      <emp:Company_Name>Cloud Computing</emp:Company_Name>
      <emp:Designation>ICT2016-112233</emp:Designation>
      <emp:Description>Provides back-end cloud hosted web services</emp:Description>
      <emp:Starting_year>2016-01-01</emp:Starting_year>
      <emp:Ending_year>2017-01-01</emp:Ending_year>
    </emp:Record>

  </emp:Records>
</emp:employmentrecords>
