=== omarnasir/ID2208_HW1/src/xsdFiles/ShortCV.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.employmentservicecompany.org/shortcv.xsd"
	xmlns:tns="http://www.employmentservicecompany.org/shortcv.xsd"
	elementFormDefault="qualified">
	<xsd:element name="shortcv">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="xsd:string" />
				<xsd:element name="phone" type="xsd:integer" />
				<xsd:element name="age" type="tns:ageType" minOccurs="0"/>
				<xsd:element name="gender" type="tns:genderType" minOccurs="0"/>
				<xsd:element name="email" type="tns:emailType" />
				<xsd:element name="prefLocation" type="xsd:string" minOccurs="0"/>
				<xsd:element name="location" type="xsd:string" 	/>
				<xsd:element name="objective" type="xsd:string" />
				<xsd:element name="tarIndustry" type="xsd:string" />
				<xsd:element name="languages">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="language" type="xsd:string" minOccurs="0"
								maxOccurs="5" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="skills">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="skill" type="xsd:string" minOccurs="0"
								maxOccurs="5" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="references">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="reference" type="xsd:string" minOccurs="0"
								maxOccurs="5" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:simpleType name="ageType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="100" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="genderType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="male|female" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="emailType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[^@]+@[^\.]+\..+" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== omarnasir/ID2208_HW1/xmlFiles/ShortCV.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv:shortcv xmlns:cv="http://www.employmentservicecompany.org/shortcv.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.employmentservicecompany.org/shortcv.xsd ../xsdFiles/ShortCV.xsd ">
  <cv:name></cv:name>
  <cv:phone>0765223344</cv:phone>
  <cv:age>20</cv:age>
  <cv:gender>male</cv:gender>
  <cv:email>example@gmail.com</cv:email>
  <cv:prefLocation>Stockholm</cv:prefLocation>
  <cv:location>London</cv:location>
  <cv:objective>To work at a software development company</cv:objective>
  <cv:tarIndustry>ICT</cv:tarIndustry>
  <cv:language>English</cv:language>
  <cv:language>Swedish</cv:language>
  <cv:skills>C++</cv:skills>
  <cv:skills>Java</cv:skills>
  <cv:skills>SQL</cv:skills>
  <cv:references>Manager Mr. XYZ at ABC Corp</cv:references>
</cv:shortcv>

=== omarnasir/ID2208_HW1/src/xmlFiles/ShortCV.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv:shortcv xmlns:cv="http://www.employmentservicecompany.org/shortcv.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.employmentservicecompany.org/shortcv.xsd ../xsdFiles/ShortCV.xsd ">
	<cv:name>Mr. XYZ</cv:name>
	<cv:phone>0765223344</cv:phone>
	<cv:age>20</cv:age>
	<cv:gender>male</cv:gender>
	<cv:email>example@gmail.com</cv:email>
	<cv:prefLocation>Stockholm</cv:prefLocation>
	<cv:location>London</cv:location>
	<cv:objective>To work at a software development company</cv:objective>
	<cv:tarIndustry>ICT</cv:tarIndustry>
	<cv:languages>
		<cv:language>English</cv:language>
		<cv:language>Swedish</cv:language>
	</cv:languages>
	<cv:skills>
		<cv:skill>C++</cv:skill>
		<cv:skill>Java</cv:skill>
	</cv:skills>
	<cv:references>
		<cv:reference>Manager Mr. XYZ at ABC Corp</cv:reference>
	</cv:references>
</cv:shortcv>
