=== omarnasir/ID2208_HW1/src/xsdFiles/Transcript.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.employmentservicecompany.org/transcript.xsd"
	xmlns:tns="http://www.employmentservicecompany.org/transcript.xsd"
	elementFormDefault="qualified">
	<xsd:element name="Transcript">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Name" type="xsd:string" minOccurs="1" />
				<xsd:element name="StudentID" type="xsd:int" minOccurs="1" />
				<xsd:element name="University" type="xsd:string"
					minOccurs="1" />
				<xsd:element name="Degree" type="xsd:string" />
				<xsd:element name="Startingyear" type="tns:StartingyearType" />
				<xsd:element name="Endingyear" type="tns:EndingyearType" />
				<xsd:element name="Courses">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Course" minOccurs="1" maxOccurs="30">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Code" type="tns:CodeType"
											minOccurs="1" maxOccurs="1" />
										<xsd:element name="Name" type="xsd:string"
											minOccurs="1" maxOccurs="1" />
										<xsd:element name="Grade" type="tns:GradeType"
											minOccurs="1" maxOccurs="1" />
										<xsd:element name="Credits" type="tns:GreditsType"
											minOccurs="1" maxOccurs="1" />
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="StartingyearType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1900" />
			<xsd:maxInclusive value="2017" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="EndingyearType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1900" />
			<xsd:maxInclusive value="2017" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CodeType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Z]{2}[0-9]{4}" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="GradeType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-F]" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="GreditsType">
		<xsd:restriction base="xsd:decimal">
			<xsd:minInclusive value="1.0" />
			<xsd:maxInclusive value="5.0" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== omarnasir/ID2208_HW1/src/xmlFiles/Transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<Transcript xmlns:tran="http://www.employmentservicecompany.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 	xsi:schemaLocation="http://www.employmentservicecompany.org/transcript.xsd ../xsdFiles/Transcript.xsd ">
  <tran:Name>Peter</tran:Name>
  <tran:StudentID>333</tran:StudentID>
  <tran:University>WUT</tran:University>
  <tran:Degree>PHD</tran:Degree>
  <tran:Startingyear>1900</tran:Startingyear>
  <tran:Endingyear>1904</tran:Endingyear>
  <tran:Courses>
    <!--1 to 30 repetitions:-->
    <tran:Course>
      <tran:Code>DH9900</tran:Code>
      <tran:Name>Signal Theory</tran:Name>
      <tran:Grade>3.5</tran:Grade>
      <tran:Credits>5.0</tran:Credits>
    </tran:Course>
    <tran:Course>
      <tran:Code>CV9999</tran:Code>
      <tran:Name>Computer Vision</tran:Name>
      <tran:Grade>4</tran:Grade>
      <tran:Credits>4.5</tran:Credits>
    </tran:Course>
    <tran:Course>
      <tran:Code>ML9990</tran:Code>
      <tran:Name>Machine learning</tran:Name>
      <tran:Grade>5</tran:Grade>
      <tran:Credits>4.0</tran:Credits>
    </tran:Course>
    <tran:Course>
      <tran:Code>PB2211</tran:Code>
      <tran:Name>Programming Basic</tran:Name>
      <tran:Grade>5</tran:Grade>
      <tran:Credits>5.0</tran:Credits>
    </tran:Course>
    <tran:Course>
      <tran:Code>WA0099</tran:Code>
      <tran:Name>Web Application</tran:Name>
      <tran:Grade>5</tran:Grade>
      <tran:Credits>5.0</tran:Credits>
    </tran:Course>
  </tran:Courses>
</Transcript>
